---
name: UpdateStoreData

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: '7.2'
            extensions: ioncube

      - name: Run update
        run: php updateData.php

      - name: Commit and push on changes
        run: |-
          git add .
          git diff
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "Updated Store Data" -a || echo "No changes to commit"
          git push
